"""Build data.js from Yahoo Finance JSON. Timestamps are interpreted in KST (Asia/Seoul).

Yahoo quirks handled here:
  * Monthly bars are timestamped at the START of the month in KST; the bar's close is
    that month's CLOSE. So bar(KST 2026-06-01) == June close == daily 2026-06-30.
    We label it by its KST month and PLOT it at the month end (where the close occurs).
  * The monthly series may end with a live intraday quote (not month-start midnight);
    we drop it and recompute the in-progress month from daily data.
  * Daily bars are UTC-midnight; their date needs no shift.
"""
import json, datetime, calendar

CUT = datetime.date(2026, 7, 15)
KST = 32400

def _result(f):
    return json.load(open(f))['chart']['result'][0]

def daily_rows(f):
    r = _result(f); ts = r['timestamp']; c = r['indicators']['quote'][0]['close']
    out = []
    for t, v in zip(ts, c):
        if v is None: continue
        d = datetime.datetime.utcfromtimestamp(t + KST).date()
        if d <= CUT: out.append((d, round(v, 1)))
    return out

def month_bars(f):
    """-> {(year,month): close} using KST month-start bars only (drops live quote)."""
    r = _result(f); ts = r['timestamp']; c = r['indicators']['quote'][0]['close']
    out = {}
    for t, v in zip(ts, c):
        if v is None: continue
        k = datetime.datetime.utcfromtimestamp(t + KST)
        if k.day != 1 or k.hour != 0:   # live/partial quote, not a real month bar
            continue
        out[(k.year, k.month)] = round(v, 1)
    return out

def xyear(d):
    return round(d.year + (d - datetime.date(d.year, 1, 1)).days / 365.25, 4)

def month_end(y, m):
    return datetime.date(y, m, calendar.monthrange(y, m)[1])

def monthly_series(fm, fd):
    """Monthly closes plotted at month end, cut at CUT; in-progress month from daily."""
    bars = month_bars(fm); dly = daily_rows(fd)
    pts = []
    for (y, m), v in sorted(bars.items()):
        end = month_end(y, m)
        if end > CUT:            # in-progress / future month -> handle via daily
            continue
        pts.append({"x": xyear(end), "v": v, "d": f"{y}.{m}"})
    if dly:                      # in-progress month (contains CUT)
        ld, lv = dly[-1]
        if not pts or (ld.year, ld.month) != tuple(int(p) for p in pts[-1]["d"].split(".")):
            pts.append({"x": xyear(ld), "v": lv, "d": f"{ld.year}.{ld.month}"})
    return pts, dly

K_M, K_D = monthly_series('kospi_mo.json', 'kospi_d.json')
S_M, S_D = monthly_series('sec_mo.json',   'sec_d.json')
H_M, H_D = monthly_series('hynix_mo.json', 'hynix_d.json')

# --- KOSPI full history: curated 1980~1996 head + real monthly ---
HEAD = [{"x":1980.0,"y":100,"d":"1980.1.4"},{"x":1985.0,"y":140,"d":"1985"},{"x":1987.0,"y":525,"d":"1987"},
 {"x":1988.0,"y":907,"d":"1988"},{"x":1989.25,"y":1003,"d":"1989.3"},{"x":1989.9,"y":909,"d":"1989.12"},
 {"x":1990.7,"y":560,"d":"1990.9"},{"x":1992.6,"y":459,"d":"1992.8"},{"x":1994.8,"y":1027,"d":"1994.10"},
 {"x":1996.0,"y":880,"d":"1996"}]
full = HEAD + [{"x": p["x"], "y": p["v"], "d": p["d"]} for p in K_M]

def cross(s, L):
    """Interpolate x where a series first rises through L (monthly resolution)."""
    for i in range(1, len(s)):
        a, b = s[i-1], s[i]
        if a['y'] < L <= b['y']:
            t = (L - a['y']) / (b['y'] - a['y'])
            return round(a['x'] + t * (b['x'] - a['x']), 3)
    return None

# Milestones = first daily CLOSE >= level (exact 경신일). Daily data starts 2020,
# so 1,000 / 2,000 keep their known historical breach dates.
# Validation: this method reproduces the known 3,000 breach (2021-01-07) exactly.
miles = [
    {"x": 1980.0,   "y": 100,  "d": "1980.1.4",  "t": "기준점 100",   "lab": 100},
    {"x": 1989.246, "y": 1003, "d": "1989.3.31", "t": "1,000 돌파", "lab": 1000},
    {"x": 2007.562, "y": 2004, "d": "2007.7.25", "t": "2,000 돌파", "lab": 2000},
]
for L in [3000, 4000, 5000, 6000, 7000, 8000]:
    hit = next(((d, v) for d, v in K_D if v >= L), None)
    if hit:
        d, v = hit
        miles.append({"x": xyear(d), "y": v, "d": f"{d.year}.{d.month}.{d.day}",
                      "t": f"{L:,} 돌파", "lab": L})

def cut2020(pts): return [p for p in pts if p["x"] >= 2020.0]
def dfmt(rows):
    return [{"x": xyear(d), "v": v, "d": f"{d.year}.{d.month:02d}.{d.day:02d}"}
            for d, v in rows if d >= datetime.date(2020, 1, 1)]

def arrp(a): return "[\n" + ",\n".join(" " + json.dumps(o, ensure_ascii=False) for o in a) + "\n]"
def arrc(a): return "[" + ",".join(json.dumps(o, ensure_ascii=False, separators=(',', ':')) for o in a) + "]"

with open('data.js', 'w') as f:
    f.write("// Auto-generated by gen_data.py from Yahoo Finance (KRX). Data through 2026-07-15.\n")
    f.write("// Timestamps interpreted in KST. Monthly close plotted at month end.\n")
    f.write("// KOSPI: curated 1980~1996 head + real monthly 1996-12~2026-07.\n")
    f.write("const KOSPI_SERIES=" + arrp(full) + ";\n\nconst KOSPI_MILES=" + arrp(miles) + ";\n\n")
    f.write("// 2020-01~2026-07-15 monthly actual values (overview).\n")
    f.write("const CMP_KOSPI=" + arrp(cut2020(K_M)) + ";\n\nconst CMP_SEC=" + arrp(cut2020(S_M)) + ";\n\nconst CMP_HYNIX=" + arrp(cut2020(H_M)) + ";\n\n")
    f.write("// DAILY actual values through 2026-07-15. x=frac year, v=close, d=YYYY.MM.DD.\n")
    f.write("const DAILY_KOSPI=" + arrc(dfmt(K_D)) + ";\n\nconst DAILY_SEC=" + arrc(dfmt(S_D)) + ";\n\nconst DAILY_HYNIX=" + arrc(dfmt(H_D)) + ";\n")

# ---- sanity checks ----
dk = dict(K_D)
print("KOSPI monthly tail:", K_M[-4:])
print()
print("CHECK monthly close == that month's last daily close:")
for p in K_M[-4:]:
    y, m = map(int, p["d"].split("."))
    days = [d for d in dk if d.year == y and d.month == m]
    last = max(days)
    ok = abs(dk[last] - p["v"]) < 0.5
    print(f"  {p['d']:>8}  monthly={p['v']:<9} last daily({last})={dk[last]:<9} {'OK' if ok else 'MISMATCH'}")
print()
print("milestones:"); [print("  ", m) for m in miles]
print()
print("daily counts:", len(dfmt(K_D)), len(dfmt(S_D)), len(dfmt(H_D)))
print("last daily:", dfmt(K_D)[-1], dfmt(S_D)[-1], dfmt(H_D)[-1])
